#!/bin/bash

rm pids
touch pids

calc() {
    echo "$2 $BASHPID" >> $1  

    local a=1
    while [ 1 ]
    do
         let a=$a*2
    done
}


calc pids 1 &
calc pids 2 &
calc pids 3 &

echo "running"
pid=$(cat pids | grep -E "^1 " | awk '{print $2}')
echo $pid

cpulimit -p $pid -l 10 &


